

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: scheduler
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: ./scheduler_api/app
    environment:
      POSTGRES_URI: postgresql+asyncpg://user:pass@db:5432/scheduler
      DB_URL: postgresql+psycopg2://user:pass@db:5432/scheduler
      JWT_SECRET: your_strong_secret_here
    ports:
      - "8000:8000"
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  ui:
    build: ./scheduler_ui
    environment:
      API_URL: http://api:8000
      JWT_SECRET: your_strong_secret_here
    ports:
      - "8501:8501"
    depends_on:
      api:
        condition: service_healthy

volumes:
  pgdata: